### ISSUE TITLE
Take another pass at the RAG pipeline

### ISSUE THREAD

**Issue by h3nd3r** [h3nd3r/nutrition_pro#1]
1. Change PDF to MD
2. Remove user_record.md from .gitignore
3. Add user_record.md to users/ folder so it's ingested into embedding
4. Work to get the prompt to return information from span of both documents
e.g.
user_record.md
## Client Information
**Name:** Jane Doe
**Age:** 30
FRE.pdf
goal is to eat healthier, more vegetables, get more fiber in my diet.

**Comment by itasari** [comment]
it should now return info from both documents. Changes pushed to main
