### ISSUE TITLE
split RAG pipeline into user history and user info

### ISSUE THREAD

**Issue by itasari** [h3nd3r/nutrition_pro#10]
Right now it's calling rag pipeline for each query. 

Potential improvements:
* Only call FRE once but can call user_records (or other potential file addition) multiple times
* Use other indexing to speed up the retrieval

**Comment by h3nd3r** [comment]
1. user info should only be called on app startup to get appended to the prompt once
2. user history we should create the embeddings once, but allow searching and pass search results to model for every user interaction

**Comment by h3nd3r** [comment]
we could copy user info into the prompt if the info is small (current case), if it were like a users medical record or something we could go to embeddings at that point (future case)

**Comment by h3nd3r** [comment]
function get_history - will query user record - to get a synopsis of how the user is doing over the course of the last week and maybe month?

**Comment by itasari** [comment]
I copied user info into the prompt and delete user_info.md. I also updated the rag_pipeline to only summarize from meal preferences. 

My thought is that "Alerts" and "Dinner Log" are handled separately in creating user response like we discussed before.

**Comment by itasari** [comment]
need to update user_info to be a separate file

**Comment by itasari** [comment]
a43f8558c1f885892c6c6f9a20afd9ee1318d050

get_history is handled in #24
