### ISSUE TITLE
Integrate Kroger product API

### ISSUE THREAD

**Issue by h3nd3r** [h3nd3r/nutrition_pro#2]
https://developer.kroger.com/reference/api/product-api-public/1.2.4?viewwith=swaggerui

Hardcode location ID for now.

We want if the user staple list is sparse or empty to use the response from the API to generate recommendations.  (Stretch) Or if the user asks for more diversity.

**Comment by itasari** [comment]
pushed the changes to ita-function-calling branch. it should now support function call when user has little pantry item or want diversity

**Comment by itasari** [comment]
merged to main
