### ISSUE TITLE
Trader Joes response cut off

### ISSUE THREAD

**Issue by itasari** [h3nd3r/nutrition_pro#23]
I noticed a few times that when I asked for trader joes items, the last entry given by ChatGPT always has the link cut off. I'm guessing the json file has too many tokens, so it got cut off trying to list everything?

<img width="673" alt="Trader joes last response cut off" src="https://github.com/user-attachments/assets/a04f440f-6031-4604-813d-39999da5c208">

@h3nd3r what do you think about just picking a few at random?

**Comment by h3nd3r** [comment]
fixed https://github.com/h3nd3r/nutrition_pro/commit/5e3455af87a43751e7accbc07ddcfa2bbef81381
