### ISSUE TITLE
API - get location for user and pass to product API

### ISSUE THREAD

**Issue by h3nd3r** [h3nd3r/nutrition_pro#3]
api reference: https://developer.kroger.com/reference/api/location-api-public

sample call:
curl -X 'GET' \
  'https://api.kroger.com/v1/locations?filter.zipCode.near={{ZIP_CODE}}&filter.radiusInMiles=10&filter.limit=10' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer {{ACCESS_TOKEN}}'

curl -X GET \
  'https://api.kroger.com/v1/locations' \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer {{ACCESS_TOKEN}}'

**Comment by itasari** [comment]
User will provide a zip code, and this will get passed into the function to then get location_id

**Comment by h3nd3r** [comment]
This works if it's in the user_info.md or not, llm will ask for it, then call the api before calling the get groceries api.
