### ISSUE TITLE
Allow user to supply own recipes

### ISSUE THREAD

**Issue by h3nd3r** [h3nd3r/nutrition_pro#6]
can we download txt or anything from recipe sites and then pull into embeddings?

**Comment by h3nd3r** [comment]
give link to recipe url and have it scrape the recipe from the webpage?

**Comment by h3nd3r** [comment]
could be a follow on to web scraper.  could be a folder with pdfs or other software integration (notion?)

**Comment by itasari** [comment]
I just pushed changes for the notion reader. It will make the connection to our notion page (that currently has 3 recipes) and can now return the formatted page content that we can now feed into the LLM.

I'll work on the LLM hook up later

**Comment by itasari** [comment]
integrate RAG with notion pages
