### ISSUE TITLE
Photo of fridge/pantry

### ISSUE THREAD

**Issue by h3nd3r** [h3nd3r/nutrition_pro#7]
Populate ingredients for LLM by using image recognition from user supplied photo of pantry/fridge/freezer

**Comment by h3nd3r** [comment]
Looked at some models on hugging face, spoiler, they didn't perform very well
<img width="1329" alt="Screenshot 2024-10-04 at 1 41 18 PM" src="https://github.com/user-attachments/assets/90b17b3e-5ece-4816-9bc7-a83d12da110b">
<img width="1328" alt="Screenshot 2024-10-04 at 1 41 52 PM" src="https://github.com/user-attachments/assets/93279a24-017e-43b7-bd01-9d2ef57972eb">
<img width="513" alt="Screenshot 2024-10-04 at 1 30 55 PM" src="https://github.com/user-attachments/assets/c4583d3c-0bf6-436d-8d14-9a6cbe9c6c26">
<img width="534" alt="Screenshot 2024-10-04 at 1 31 18 PM" src="https://github.com/user-attachments/assets/b6fde6cd-18fa-4a2a-95da-1bb75d481380">
<img width="1324" alt="Screenshot 2024-10-04 at 1 31 56 PM" src="https://github.com/user-attachments/assets/6ed7e89e-f557-4134-8411-1932c84c7ff5">
<img width="1329" alt="Screenshot 2024-10-04 at 1 32 35 PM" src="https://github.com/user-attachments/assets/ed17d471-6a40-4de5-811a-dd2a5c181972">
<img width="1300" alt="Screenshot 2024-10-04 at 1 33 03 PM" src="https://github.com/user-attachments/assets/8320088f-6277-4129-8e7f-9a95e9ea7738">

**Comment by h3nd3r** [comment]
Tried ChatGPT and Gemini, ChatGPT worked the best, but still had incorrect items identified
<img width="1104" alt="Screenshot 2024-10-04 at 1 49 43 PM" src="https://github.com/user-attachments/assets/b20c00fb-d54d-4cdd-b8a9-265ed7398fb3">
<img width="1041" alt="Screenshot 2024-10-04 at 1 51 20 PM" src="https://github.com/user-attachments/assets/95b29baf-b993-4276-ac8b-a9a21c84ab8b">
<img width="1062" alt="Screenshot 2024-10-04 at 1 53 35 PM" src="https://github.com/user-attachments/assets/917a6050-3611-425d-86ff-de8bb9202324">

**Comment by h3nd3r** [comment]
Also, gemini called my pantry disorganized, so I think we should use ChatGPT instead LOL 
<img width="788" alt="Screenshot 2024-10-04 at 1 46 26 PM" src="https://github.com/user-attachments/assets/bf05d6d6-7e4f-439a-a274-57b90db3f095">

**Comment by itasari** [comment]
it's so interesting to see what those first few models returned.... "bottle, bottle, bottle", toy store, wardrobe?? lol
Gemini is so rude :D ChatGPT is not terrible, but yea still not accurate, plus it's calling your fridge "pantry" sigh...

did you check out the new model you mentioned (from facebook?)

**Comment by h3nd3r** [comment]
@itasari no, I didn't.  the more contrived pictures are better, from the pantry still missing the quinoa and lentils, but 🤷 .  If you want a good laugh, check out some of the recipes it suggests - mix canned pumpkin, diced tomatoes and stick it in a tortilla!
<img width="820" alt="Screenshot 2024-10-08 at 1 30 56 PM" src="https://github.com/user-attachments/assets/8dbc92e1-5a60-4d75-ad5d-3e6ea06fc4e4">
<img width="841" alt="Screenshot 2024-10-08 at 1 41 55 PM" src="https://github.com/user-attachments/assets/08371e9d-63a4-488a-a578-2b75cf41eeb5">
